# Generated by Django 5.2.5 on 2025-09-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cou_name', models.CharField(max_length=50)),
                ('batch_type', models.CharField()),
                ('language', models.CharField()),
                ('dis_type', models.CharField()),
                ('final_price', models.IntegerField()),
                ('actual_price', models.IntegerField()),
                ('offer', models.IntegerField()),
                ('schedule_type', models.CharField()),
                ('total_content', models.IntegerField()),
            ],
        ),
    ]
