# Generated by Django 5.2.5 on 2025-09-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cou_name',
            field=models.CharField(),
        ),
    ]
