# Generated by Django 5.2.5 on 2025-09-25 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_cou_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='final_price',
        ),
    ]
